stages:
  - build
  - deploy

build_test:
  stage: build
  tags:
    - webpack
  only:
    - master
    - test
  cache:
    key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  script:
    - npm --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy_test:
  stage: deploy
  tags:
    - webpack
  only:
    - master
  script:
    - cp -r ./dist/static /data/apps/fxshop-h5/test/
    - cp ./dist/index.html /data/apps/fxshop-h5/test/index.html
